#include "xc7z020.h"


// FPGA matrix
const u32 fpga[MAX_ROWS][MAX_COLUMNS][2] = {
	{
		{block(BOTTOM, ROW1, IOB_A), IOBA_TYPE},
		{block(BOTTOM, ROW1, IOB_B), IOBB_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW1, BRAM), BRAM_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW1, DSP), DSP_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW1, DSP), DSP_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW1, BRAM), BRAM_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_L_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_L_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW1, BRAM), BRAM_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW1, DSP), DSP_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_L_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_L_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_L_TYPE},
		{block(BOTTOM, ROW1, CLK), CLK_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_L_TYPE},
		{block(BOTTOM, ROW1, BRAM), BRAM_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_L_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_L_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_L_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_L_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_L_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_L_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_L_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_L_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_L_TYPE},
		{block(BOTTOM, ROW1, CFG), CFG_TYPE},
		{block(BOTTOM, ROW1, CLB),  CLB_L_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_L_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_L_TYPE},
		{block(BOTTOM, ROW1, BRAM), BRAM_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW1, DSP), DSP_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW1, DSP), DSP_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW1, BRAM), BRAM_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_L_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_L_TYPE},
		{block(BOTTOM, ROW1, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW1, IOB_B), IOBB_TYPE},
		{block(BOTTOM, ROW1, IOB_A), IOBA_TYPE}
	},
	{
		{block(BOTTOM, ROW0, IOB_A), IOBA_TYPE},
		{block(BOTTOM, ROW0, IOB_B), IOBB_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW0, BRAM), BRAM_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW0, DSP), DSP_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW0, DSP), DSP_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW0, BRAM), BRAM_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_L_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_L_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW0, BRAM), BRAM_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW0, DSP), DSP_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_L_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_L_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_L_TYPE},
		{block(BOTTOM, ROW0, CLK), CLK_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_L_TYPE},
		{block(BOTTOM, ROW0, BRAM), BRAM_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_L_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_L_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_L_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_L_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_L_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_L_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_L_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_L_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_L_TYPE},
		{block(BOTTOM, ROW0, CFG), CFG_TYPE},
		{block(BOTTOM, ROW0, CLB),  CLB_L_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_L_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_L_TYPE},
		{block(BOTTOM, ROW0, BRAM), BRAM_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW0, DSP), DSP_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW0, DSP), DSP_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW0, BRAM), BRAM_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_L_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_L_TYPE},
		{block(BOTTOM, ROW0, CLB), CLB_M_TYPE},
		{block(BOTTOM, ROW0, IOB_B), IOBB_TYPE},
		{block(BOTTOM, ROW0, IOB_A), IOBA_TYPE}
	},
	{
		{block(TOP, ROW0, IOB_A), IOBA_TYPE},
		{block(TOP, ROW0, IOB_B), IOBB_TYPE},
		{block(TOP, ROW0, CLB), CLB_M_TYPE},
		{block(TOP, ROW0, CLB), CLB_M_TYPE},
		{block(TOP, ROW0, CLB), CLB_M_TYPE},
		{block(TOP, ROW0, CLB), CLB_M_TYPE},
		{block(TOP, ROW0, BRAM), BRAM_TYPE},
		{block(TOP, ROW0, CLB), CLB_M_TYPE},
		{block(TOP, ROW0, CLB), CLB_M_TYPE},
		{block(TOP, ROW0, DSP), DSP_TYPE},
		{block(TOP, ROW0, CLB), CLB_M_TYPE},
		{block(TOP, ROW0, CLB), CLB_M_TYPE},
		{block(TOP, ROW0, CLB), CLB_M_TYPE},
		{block(TOP, ROW0, CLB), CLB_M_TYPE},
		{block(TOP, ROW0, DSP), DSP_TYPE},
		{block(TOP, ROW0, CLB), CLB_M_TYPE},
		{block(TOP, ROW0, CLB), CLB_M_TYPE},
		{block(TOP, ROW0, BRAM), BRAM_TYPE},
		{block(TOP, ROW0, CLB), CLB_L_TYPE},
		{block(TOP, ROW0, CLB), CLB_M_TYPE},
		{block(TOP, ROW0, CLB), CLB_L_TYPE},
		{block(TOP, ROW0, CLB), CLB_M_TYPE},
		{block(TOP, ROW0, BRAM), BRAM_TYPE},
		{block(TOP, ROW0, CLB), CLB_M_TYPE},
		{block(TOP, ROW0, CLB), CLB_M_TYPE},
		{block(TOP, ROW0, DSP), DSP_TYPE},
		{block(TOP, ROW0, CLB), CLB_M_TYPE},
		{block(TOP, ROW0, CLB), CLB_M_TYPE},
		{block(TOP, ROW0, CLB), CLB_L_TYPE},
		{block(TOP, ROW0, CLB), CLB_M_TYPE},
		{block(TOP, ROW0, CLB), CLB_L_TYPE},
		{block(TOP, ROW0, CLB), CLB_M_TYPE},
		{block(TOP, ROW0, CLB), CLB_L_TYPE},
		{block(TOP, ROW0, CLK), CLK_TYPE},
		{block(TOP, ROW0, CLB), CLB_M_TYPE},
		{block(TOP, ROW0, CLB), CLB_L_TYPE},
		{block(TOP, ROW0, BRAM), BRAM_TYPE},
		{block(TOP, ROW0, CLB), CLB_M_TYPE},
		{block(TOP, ROW0, CLB), CLB_L_TYPE},
		{block(TOP, ROW0, CLB), CLB_M_TYPE},
		{block(TOP, ROW0, CLB), CLB_L_TYPE},
		{block(TOP, ROW0, CLB), CLB_M_TYPE},
		{block(TOP, ROW0, CLB), CLB_L_TYPE},
		{block(TOP, ROW0, CLB), CLB_M_TYPE},
		{block(TOP, ROW0, CLB), CLB_L_TYPE},
		{block(TOP, ROW0, CLB), CLB_L_TYPE},
		{block(TOP, ROW0, CLB), CLB_L_TYPE},
		{block(TOP, ROW0, CLB), CLB_L_TYPE},
		{block(TOP, ROW0, CLB), CLB_L_TYPE},
		{block(TOP, ROW0, CLB), CLB_L_TYPE},
		{block(TOP, ROW0, CFG), CFG_TYPE},
		{block(TOP, ROW0, CLB),  CLB_L_TYPE},
		{block(TOP, ROW0, CLB), CLB_M_TYPE},
		{block(TOP, ROW0, CLB), CLB_L_TYPE},
		{block(TOP, ROW0, CLB), CLB_M_TYPE},
		{block(TOP, ROW0, CLB), CLB_L_TYPE},
		{block(TOP, ROW0, BRAM), BRAM_TYPE},
		{block(TOP, ROW0, CLB), CLB_M_TYPE},
		{block(TOP, ROW0, CLB), CLB_M_TYPE},
		{block(TOP, ROW0, DSP), DSP_TYPE},
		{block(TOP, ROW0, CLB), CLB_M_TYPE},
		{block(TOP, ROW0, CLB), CLB_M_TYPE},
		{block(TOP, ROW0, CLB), CLB_M_TYPE},
		{block(TOP, ROW0, CLB), CLB_M_TYPE},
		{block(TOP, ROW0, DSP), DSP_TYPE},
		{block(TOP, ROW0, CLB), CLB_M_TYPE},
		{block(TOP, ROW0, CLB), CLB_M_TYPE},
		{block(TOP, ROW0, BRAM), BRAM_TYPE},
		{block(TOP, ROW0, CLB), CLB_L_TYPE},
		{block(TOP, ROW0, CLB), CLB_M_TYPE},
		{block(TOP, ROW0, CLB), CLB_L_TYPE},
		{block(TOP, ROW0, CLB), CLB_M_TYPE},
		{block(TOP, ROW0, IOB_B), IOBB_TYPE},
		{block(TOP, ROW0, IOB_A), IOBA_TYPE}
	}
};

// FPGA bram matrix
const u32 fpga_bram[MAX_ROWS][MAX_COLUMNS] = {
	{
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_CONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_CONTENT, 1),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_CONTENT, 2),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_CONTENT, 3),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_CONTENT, 4),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_CONTENT, 5),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0)
	},
	{
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_CONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_CONTENT, 1),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_CONTENT, 2),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_CONTENT, 3),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_CONTENT, 4),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_CONTENT, 5),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0)
	},
	{
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_CONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_CONTENT, 1),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_CONTENT, 2),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_CONTENT, 3),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_CONTENT, 4),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_CONTENT, 5),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0),
		content(BRAM_NOCONTENT, 0)
	}
};